use_frameworks!

use_modular_headers!
inhibit_all_warnings!

target 'KSCircleProgressView_Example' do
  pod 'KSCircleProgressView', :path => '../'
  
  # demo 使用
  pod 'RxSwift', '~> 4.0' # Rx
  pod 'RxCocoa', '~> 4.0' # Rx
  pod 'SnapKit' # Autolayout

  target 'KSCircleProgressView_Tests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
