#use_frameworks!

platform :ios, '8.0'

use_modular_headers!
inhibit_all_warnings!

target 'KSCircleProgressView' do
    pod 'RxSwift', '~> 4.0' # Rx
    pod 'RxCocoa', '~> 4.0' # Rx
    pod 'SnapKit' # Autolayout
end
